### ISSUE TITLE
I have problem with Gradle :(

### ISSUE THREAD

**Issue by ghost** [cout970/Modeler#5]
Hello  everyone,

I have tried to able gradle project but it seems always "FAILED BUILD" 

And i can't get successful. Gradle is really shit please use ant or maven or without extra compiler

**Comment by cout970** [comment]
Tbh I don't like gradle too much but it works, what doesn't work so well, is the code, and that my fault for not updating the project in a while, so you could either use an older version, or just wait for an update.

**Comment by cout970** [comment]
Updated

**Comment by ghost** [comment]
Okay thanks for note! :)
