### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by MrTubzy456** [cout970/Modeler#6]
Minecraft version: 1.12.2
forge version: 14.23.4.2762
Modelloader version: 1.1.4

Crash report: https://pastebin.com/vJ4T8DaD

This is on a server. In single player it starts up fine but, starting up a server it crashes over and over again.

**Comment by cout970** [comment]
First, this is not the correct repo, Second, I see the problem, for now you can use the previous version which should work perfectly fine, because the only changes it adds are in systems not used by Magneticraft

**Comment by MrTubzy456** [comment]
Oh it came up as modelloader so I thought that was what it was. I already downgraded to the previous version of modelloader so that my server will run. 

If this isn’t where I should post this, where should I post it? I’m sorry for my ignorance. I thought I was helping out.

**Comment by cout970** [comment]
Don't get me wrong, you are helping me, a lot in fact, but in the curseforge page of the library there is a button `Source` which links to the [library repo](https://github.com/Magneticraft-Team/ModelLoader). This repo is for the 3D modeler, the tool to make 3D models, the library just loads those models into the game.
